import { MatchDrinkQuestion } from "./types";

export const MATCH_DRINK_QUESTIONS: MatchDrinkQuestion[] = [
  {
    id: "q1",
    text: "Quando esci in compagnia tu sei quello che:",
    category: "warmup",
    options: [
      { id: "A", text: "Organizza tutto", traits: { orgoglio: 1, fedele: 1 }, comment: "Abbiamo dei piccoli dittatori della serata in sala." },
      { id: "B", text: "Arriva tardi ma con stile", traits: { caotico: 1, ironico: 1 }, comment: "L'importante è farsi notare quando si entra." },
      { id: "C", text: "Dice “solo una birra” e mente", traits: { festaiolo: 2, caotico: 1 }, comment: "Qui nessuno sa fermarsi a 'una cosa'." },
      { id: "D", text: "Sparisce e torna con gente nuova", traits: { libero: 2, pericoloso: 1 }, comment: "I nostri PR naturali hanno colpito ancora." },
      { id: "E", text: "Dice “vengo tranquillo” e poi crea la serata", traits: { caotico: 2, festaiolo: 1 }, comment: "I 'tranquilli' sono sempre i peggiori." },
    ],
  },
  {
    id: "q2",
    text: "Davanti a un messaggio visualizzato e senza risposta tu:",
    category: "gelosia",
    options: [
      { id: "A", text: "Aspetti tranquillo", traits: { timido: 1, fedele: 1 }, comment: "Santa pazienza, o forse solo disinteresse?" },
      { id: "B", text: "Fingi tranquillità", traits: { orgoglio: 2, timido: 1 }, comment: "L'orgoglio prima di tutto, il fegato dopo." },
      { id: "C", text: "Controlli l’ultimo accesso", traits: { investigatore: 2, geloso: 1 }, comment: "Abbiamo trovato gli 007 della serata." },
      { id: "D", text: "Hai già chiesto un parere alla chat degli amici", traits: { investigatore: 1, caotico: 1 }, comment: "Il consiglio dei saggi è stato consultato." },
      { id: "E", text: "Dici “non mi interessa” mentre ti interessa moltissimo", traits: { orgoglio: 2, geloso: 2 }, comment: "La coerenza non è il nostro forte stasera." },
    ],
  },
  {
    id: "q3",
    text: "Il primo appuntamento ideale è:",
    category: "primo_appuntamento",
    options: [
      { id: "A", text: "Cena tranquilla", traits: { romantico: 2, fedele: 1 } },
      { id: "B", text: "Drink e risate", traits: { festaiolo: 1, ironico: 2 } },
      { id: "C", text: "Serata improvvisata", traits: { caotico: 2, libero: 1 } },
      { id: "D", text: "Basta che finisca con una storia da raccontare", traits: { pericoloso: 2, festaiolo: 1 } },
      { id: "E", text: "Non pianifico: se naufraghiamo, naufraghiamo", traits: { libero: 2, caotico: 1 } },
    ],
  },
  {
    id: "q4",
    text: "In amore sei più:",
    category: "personalita",
    options: [
      { id: "A", text: "Romantico", traits: { romantico: 3 } },
      { id: "B", text: "Libero", traits: { libero: 3 } },
      { id: "C", text: "Geloso", traits: { geloso: 3 } },
      { id: "D", text: "Un disastro con buone intenzioni", traits: { caotico: 2, romantico: 1 } },
      { id: "E", text: "Sereno/a fuori, sceneggiatura dentro", traits: { investigatore: 2, orgoglio: 1 } },
    ],
  },
  {
    id: "q5",
    text: "La tua red flag più onesta è:",
    category: "red_flag",
    options: [
      { id: "A", text: "Mi affeziono troppo presto", traits: { romantico: 2, fedele: 1 } },
      { id: "B", text: "Mi annoio troppo in fretta", traits: { libero: 2, pericoloso: 1 } },
      { id: "C", text: "Dico “non sono geloso/a” ma lo sono", traits: { geloso: 3, orgoglio: 1 } },
      { id: "D", text: "Faccio il duro/a ma poi ci resto male", traits: { orgoglio: 2, romantico: 1 } },
      { id: "E", text: "Dico che comunico bene, poi sparisco", traits: { timido: 2, libero: 1 } },
    ],
  },
  {
    id: "q6",
    text: "Se una persona ti piace davvero, tu:",
    category: "personalita",
    options: [
      { id: "A", text: "Lo fai capire", traits: { diretto: 3 } },
      { id: "B", text: "Fai finta di niente", traits: { timido: 2, orgoglio: 2 } },
      { id: "C", text: "Diventi improvvisamente simpatico/a", traits: { ironico: 3 } },
      { id: "D", text: "Ti comporti malissimo e poi ti chiedi perché", traits: { caotico: 3, pericoloso: 1 } },
      { id: "E", text: "Aspetto un segnale chiarissimo e poi lo ignoro", traits: { timido: 3, orgoglio: 1 } },
    ],
  },
  {
    id: "q7",
    text: "In coppia litighi di più per:",
    category: "gelosia",
    options: [
      { id: "A", text: "Gelosia", traits: { geloso: 3 } },
      { id: "B", text: "Orgoglio", traits: { orgoglio: 3 } },
      { id: "C", text: "Messaggi non risposti", traits: { investigatore: 2, geloso: 1 } },
      { id: "D", text: "Dove mangiare", traits: { romantico: 1, caotico: 1 } },
      { id: "E", text: "Il tono con cui è stata detta una cosa normale", traits: { investigatore: 1, orgoglio: 2 } },
    ],
  },
  {
    id: "q8",
    text: "Se il tuo ex entra nello stesso locale:",
    category: "show",
    options: [
      { id: "A", text: "Saluto con maturità", traits: { fedele: 2, diretto: 1 } },
      { id: "B", text: "Fingo di non vedere", traits: { timido: 2, orgoglio: 1 } },
      { id: "C", text: "Mi trasformo in una persona migliore per 12 minuti", traits: { ironico: 2, orgoglio: 2 } },
      { id: "D", text: "Ordino da bere e inizia il teatro", traits: { caotico: 2, festaiolo: 2 } },
      { id: "E", text: "Rido, ma internamente parte una serie Netflix", traits: { investigatore: 2, ironico: 1 } },
    ],
  },
  {
    id: "q9",
    text: "La frase più pericolosa da sentire è:",
    category: "red_flag",
    options: [
      { id: "A", text: "“Non sono come gli altri”", traits: { investigatore: 2, pericoloso: 1 } },
      { id: "B", text: "“Non cerco niente di serio”", traits: { libero: 2, diretto: 1 } },
      { id: "C", text: "“Ti spiego il mio rapporto con l’ex”", traits: { geloso: 2, investigatore: 2 } },
      { id: "D", text: "“Tranquillo/a, sono una persona semplice”", traits: { ironico: 2, pericoloso: 1 } },
      { id: "E", text: "“Io non sono geloso/a”", traits: { orgoglio: 2, geloso: 2 } },
    ],
  },
  {
    id: "q10",
    text: "Quando dici “non mi interessa”, di solito significa:",
    category: "personalita",
    options: [
      { id: "A", text: "Non mi interessa davvero", traits: { diretto: 3 } },
      { id: "B", text: "Mi interessa ma non lo ammetto", traits: { orgoglio: 3 } },
      { id: "C", text: "Mi interessa tantissimo", traits: { romantico: 2, geloso: 1 } },
      { id: "D", text: "Ho già fatto tre teorie e due screenshot", traits: { investigatore: 3 } },
      { id: "E", text: "Sto aspettando che qualcuno mi dica che ho ragione", traits: { orgoglio: 2, romantico: 1 } },
    ],
  },
  {
    id: "q11",
    text: "Il tuo stile di corteggiamento è:",
    category: "primo_appuntamento",
    options: [
      { id: "A", text: "Elegante", traits: { romantico: 2, orgoglio: 1 } },
      { id: "B", text: "Ironico", traits: { ironico: 3 } },
      { id: "C", text: "Diretto", traits: { diretto: 3 } },
      { id: "D", text: "Confuso ma intenso", traits: { caotico: 3, romantico: 1 } },
      { id: "E", text: "Faccio il disinteressato/a con risultati discutibili", traits: { timido: 2, orgoglio: 2 } },
    ],
  },
  {
    id: "q12",
    text: "Se una persona ti piace, il tuo peggior difetto è:",
    category: "red_flag",
    options: [
      { id: "A", text: "Mi chiudo", traits: { timido: 3 } },
      { id: "B", text: "Divento troppo presente", traits: { geloso: 2, romantico: 2 } },
      { id: "C", text: "Faccio il/la brillante", traits: { ironico: 2, festaiolo: 1 } },
      { id: "D", text: "Divento geloso/a di persone che non conosco", traits: { geloso: 3, investigatore: 1 } },
      { id: "E", text: "Analizzo cose che probabilmente non esistono", traits: { investigatore: 3 } },
    ],
  },
];
