import { NextRequest, NextResponse } from "next/server";
import { requireAdminRequest } from "@/lib/admin/server-auth";
import { getSupabaseAdmin } from "@/lib/match-drink/supabase";
export const dynamic = "force-dynamic";
const fields = "id,eyebrow,title,description,cta_label,cta_url,starts_at,ends_at,background_image_url,overlay_color,priority,published";
export async function GET(request: NextRequest) { const auth = requireAdminRequest(request); if (!auth.ok) return auth.response; const {data,error}=await getSupabaseAdmin().from("highlight_contents").select(fields).order("priority",{ascending:false}); return error ? NextResponse.json({error:error.message},{status:500}) : NextResponse.json({items:data??[]}); }
export async function POST(request: NextRequest) { const auth=requireAdminRequest(request); if(!auth.ok)return auth.response; const body=await request.json(); const item={eyebrow:String(body.eyebrow??"").trim(),title:String(body.title??"").trim(),description:String(body.description??"").trim(),cta_label:String(body.cta_label??"").trim(),cta_url:String(body.cta_url??"").trim(),starts_at:body.starts_at,ends_at:body.ends_at||null,background_image_url:body.background_image_url||null,overlay_color:body.overlay_color||null,priority:Number(body.priority??0),published:body.published!==false}; if(!item.title||!item.description||!item.cta_label||!item.cta_url||!item.starts_at)return NextResponse.json({error:"Compila tutti i campi obbligatori."},{status:400}); const query=body.id?getSupabaseAdmin().from("highlight_contents").update(item).eq("id",body.id):getSupabaseAdmin().from("highlight_contents").insert(item); const {data,error}=await query.select(fields).single(); return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({item:data}); }
export async function DELETE(request: NextRequest) { const auth=requireAdminRequest(request); if(!auth.ok)return auth.response; const id=new URL(request.url).searchParams.get("id"); if(!id)return NextResponse.json({error:"ID mancante"},{status:400}); const {error}=await getSupabaseAdmin().from("highlight_contents").delete().eq("id",id); return error?NextResponse.json({error:error.message},{status:500}):NextResponse.json({success:true}); }

