"use client";
import { useEffect, useState } from "react";
type Item={id?:string;eyebrow:string;title:string;description:string;cta_label:string;cta_url:string;starts_at:string;ends_at:string;background_image_url:string;overlay_color:string;priority:number;published:boolean};
const blank:Item={eyebrow:"",title:"",description:"",cta_label:"Prenota",cta_url:"",starts_at:"",ends_at:"",background_image_url:"",overlay_color:"rgba(15,18,16,.62)",priority:0,published:true};
export default function HighlightsAdmin(){const [form,setForm]=useState(blank);const [items,setItems]=useState<Item[]>([]);const [msg,setMsg]=useState("");const load=()=>fetch("/api/highlights/admin").then(r=>r.json()).then(b=>setItems(b.items||[]));useEffect(()=>{void load()},[]);const save=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch("/api/highlights/admin",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const b=await r.json();setMsg(r.ok?"Salvato":"Errore: "+(b.error||"impossibile salvare"));if(r.ok){setForm(blank);void load()}};return <main className="min-h-screen bg-[#0a0a0a] p-6 text-white"><h1 className="mb-6 text-2xl font-black">Contenuti in evidenza</h1><form onSubmit={save} className="grid max-w-2xl gap-3">{([['eyebrow','Eyebrow'],['title','Titolo'],['description','Descrizione'],['cta_label','Testo CTA'],['cta_url','Link CTA (URL o percorso libero)'],['starts_at','Dal'],['ends_at','Al'],['background_image_url','Immagine di sfondo'],['priority','Priorità']] as const).map(([key,label])=><label key={key} className="grid gap-1 text-sm"><span>{label}</span><input type={key==='priority'?'number':key.includes('_at')?'datetime-local':'text'} placeholder={key==='cta_url'?'https://esempio.it oppure /pagina':''} value={String(form[key]??'')} onChange={e=>setForm({...form,[key]:key==='priority'?Number(e.target.value):e.target.value})} className="rounded-lg border border-white/15 bg-white/5 px-3 py-2" /></label>)}<OverlayColorControl value={form.overlay_color} onChange={(overlay_color)=>setForm({...form,overlay_color})}/><label><input type="checkbox" checked={form.published} onChange={e=>setForm({...form,published:e.target.checked})}/> Pubblicato</label><button className="rounded-lg bg-[var(--accent-strong)] px-4 py-3 font-bold">Salva contenuto</button>{msg&&<p>{msg}</p>}</form><div className="mt-8 max-w-2xl space-y-2">{items.map(x=><div key={x.id} className="flex justify-between rounded-lg border border-white/10 p-3"><span>{x.title}</span><button onClick={()=>setForm(x)} className="text-[var(--accent-strong)]">Modifica</button><button onClick={()=>fetch('/api/highlights/admin?id='+x.id,{method:'DELETE'}).then(load)} className="text-red-300">Elimina</button></div>)}</div></main>}


function OverlayColorControl({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const match = value.match(/rgba?\((\d+),\s*(\d+),\s*(\d+)(?:,\s*([\d.]+))?\)/i);
  const red = Number(match?.[1] ?? 15); const green = Number(match?.[2] ?? 18); const blue = Number(match?.[3] ?? 16);
  const alpha = Math.round(Number(match?.[4] ?? .62) * 100);
  const hex = `#${[red, green, blue].map((part) => part.toString(16).padStart(2, "0")).join("")}`;
  const update = (nextHex: string, nextAlpha: number) => { const clean = nextHex.replace("#", ""); const parts = [0, 2, 4].map((offset) => Number.parseInt(clean.slice(offset, offset + 2), 16)); onChange(`rgba(${parts[0]}, ${parts[1]}, ${parts[2]}, ${(nextAlpha / 100).toFixed(2)})`); };
  return <label className="grid gap-2 text-sm"><span>Colore overlay</span><div className="flex items-center gap-3 rounded-lg border border-white/15 bg-white/5 px-3 py-2"><input aria-label="Colore overlay" type="color" value={hex} onChange={(event) => update(event.target.value, alpha)} className="h-9 w-12 cursor-pointer rounded border-0 bg-transparent p-0" /><input aria-label="Trasparenza overlay" type="range" min="0" max="100" value={alpha} onChange={(event) => update(hex, Number(event.target.value))} className="flex-1 accent-[var(--accent-strong)]" /><strong className="w-10 text-right text-xs">{alpha}%</strong></div><code className="text-xs text-white/60">{value}</code></label>;
}
